"""crear_tablas_tenant

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-01 23:13:29.127026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('precio_bob', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cuota_almacenamiento_gb', sa.Integer(), nullable=False),
    sa.Column('cuota_inmuebles', sa.Integer(), nullable=False),
    sa.Column('cuota_reconstrucciones_mes', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'activo'"), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('token_unico', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_unico')
    )
    op.create_table('suscripcion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('trial_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_facturacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suscripcion_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('payload_firmado', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_facturacion')
    op.drop_table('suscripcion')
    op.drop_table('invitacion')
    op.drop_table('tenant')
    op.drop_table('plan')
    # ### end Alembic commands ###
