"""Additive HU-005 trial and monthly subscription persistence."""
import sqlalchemy as sa; from sqlalchemy.dialects import postgresql; from alembic import op
revision = "0005"; down_revision = "0004"; branch_labels = None; depends_on = None
def upgrade() -> None:
    op.add_column("suscripcion", sa.Column("trial_inicio", sa.DateTime(timezone=True), nullable=True)); op.add_column("suscripcion", sa.Column("periodo_inicio", sa.DateTime(timezone=True), nullable=True))
    op.create_table("tenant_administrator", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("usuario_global_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("invitacion_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("desactivado_en", sa.DateTime(timezone=True), nullable=True), sa.PrimaryKeyConstraint("id", name="pk_tenant_administrator"), sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], name="fk_tenant_administrator_tenant"), sa.ForeignKeyConstraint(["usuario_global_id"], ["usuario_global.id"], name="fk_tenant_administrator_usuario_global"), sa.ForeignKeyConstraint(["invitacion_id"], ["invitacion.id"], name="fk_tenant_administrator_invitacion"), sa.UniqueConstraint("tenant_id", "usuario_global_id", name="uq_tenant_administrator_tenant_usuario"), sa.UniqueConstraint("invitacion_id", name="uq_tenant_administrator_invitacion"))
    op.create_index("ix_tenant_administrator_usuario_activo", "tenant_administrator", ["usuario_global_id", "activo"]); op.create_index("ix_tenant_administrator_tenant_activo", "tenant_administrator", ["tenant_id", "activo"]); op.add_column("evento_facturacion", sa.Column("resultado_periodo_inicio", sa.DateTime(timezone=True), nullable=True)); op.add_column("evento_facturacion", sa.Column("resultado_periodo_fin", sa.DateTime(timezone=True), nullable=True))
def _has_data(conn: sa.Connection, table: sa.Table, condition: object = None) -> bool:
    query = sa.select(sa.literal(True)).select_from(table); query = query.where(condition) if condition is not None else query; return conn.scalar(query.limit(1)) is not None
def downgrade() -> None:
    conn = op.get_bind(); admin = sa.table("tenant_administrator", sa.column("id", postgresql.UUID(as_uuid=True))); subscription = sa.table("suscripcion", sa.column("trial_inicio", sa.DateTime(timezone=True)), sa.column("periodo_inicio", sa.DateTime(timezone=True))); event = sa.table("evento_facturacion", sa.column("tipo", sa.String()), sa.column("resultado_periodo_inicio", sa.DateTime(timezone=True)), sa.column("resultado_periodo_fin", sa.DateTime(timezone=True)))
    if _has_data(conn, admin) or _has_data(conn, subscription, sa.or_(subscription.c.trial_inicio.is_not(None), subscription.c.periodo_inicio.is_not(None))) or _has_data(conn, event, sa.or_(event.c.tipo == "subscription.monthly.succeeded", event.c.tipo.ilike("%monthly%"), event.c.tipo.ilike("%mensual%"), event.c.resultado_periodo_inicio.is_not(None), event.c.resultado_periodo_fin.is_not(None))): raise RuntimeError("No se puede degradar con datos de HU-005")
    op.drop_index("ix_tenant_administrator_usuario_activo", table_name="tenant_administrator"); op.drop_index("ix_tenant_administrator_tenant_activo", table_name="tenant_administrator"); [op.drop_constraint(name, "tenant_administrator", type_=kind) for name, kind in (("uq_tenant_administrator_tenant_usuario", "unique"), ("uq_tenant_administrator_invitacion", "unique"), ("fk_tenant_administrator_tenant", "foreignkey"), ("fk_tenant_administrator_usuario_global", "foreignkey"), ("fk_tenant_administrator_invitacion", "foreignkey"))]; op.drop_table("tenant_administrator"); op.drop_column("evento_facturacion", "resultado_periodo_fin"); op.drop_column("evento_facturacion", "resultado_periodo_inicio"); op.drop_column("suscripcion", "periodo_inicio"); op.drop_column("suscripcion", "trial_inicio")
